package com.gmail.realtadukoo.TB.Constants.Verses;

public class Job{
	public static final int CHP1 = 22;
	public static final int CHP2 = 13;
	public static final int CHP3 = 26;
	public static final int CHP4 = 21;
	public static final int CHP5 = 27;
	public static final int CHP6 = 30;
	public static final int CHP7 = 21;
	public static final int CHP8 = 22;
	public static final int CHP9 = 35;
	public static final int CHP10 = 22;
	public static final int CHP11 = 20;
	public static final int CHP12 = 25;
	public static final int CHP13 = 28;
	public static final int CHP14 = 22;
	public static final int CHP15 = 35;
	public static final int CHP16 = 22;
	public static final int CHP17 = 16;
	public static final int CHP18 = 21;
	public static final int CHP19 = 29;
	public static final int CHP20 = 29;
	public static final int CHP21 = 34;
	public static final int CHP22 = 30;
	public static final int CHP23 = 17;
	public static final int CHP24 = 25;
	public static final int CHP25 = 6;
	public static final int CHP26 = 14;
	public static final int CHP27 = 23;
	public static final int CHP28 = 28;
	public static final int CHP29 = 25;
	public static final int CHP30 = 31;
	public static final int CHP31 = 40;
	public static final int CHP32 = 22;
	public static final int CHP33 = 33;
	public static final int CHP34 = 37;
	public static final int CHP35 = 16;
	public static final int CHP36 = 33;
	public static final int CHP37 = 24;
	public static final int CHP38 = 41;
	public static final int CHP39 = 30;
	public static final int CHP40 = 24;
	public static final int CHP41 = 34;
	public static final int CHP42 = 17;
}
