package com.gmail.realtadukoo.TB.Constants.Verses;

public class SecondChronicles{
	public static final int CHP1 = 17;
	public static final int CHP2 = 18;
	public static final int CHP3 = 17;
	public static final int CHP4 = 22;
	public static final int CHP5 = 14;
	public static final int CHP6 = 42;
	public static final int CHP7 = 22;
	public static final int CHP8 = 18;
	public static final int CHP9 = 31;
	public static final int CHP10 = 19;
	public static final int CHP11 = 23;
	public static final int CHP12 = 16;
	public static final int CHP13 = 22;
	public static final int CHP14 = 15;
	public static final int CHP15 = 19;
	public static final int CHP16 = 14;
	public static final int CHP17 = 19;
	public static final int CHP18 = 34;
	public static final int CHP19 = 11;
	public static final int CHP20 = 37;
	public static final int CHP21 = 20;
	public static final int CHP22 = 12;
	public static final int CHP23 = 21;
	public static final int CHP24 = 27;
	public static final int CHP25 = 28;
	public static final int CHP26 = 23;
	public static final int CHP27 = 9;
	public static final int CHP28 = 27;
	public static final int CHP29 = 36;
	public static final int CHP30 = 27;
	public static final int CHP31 = 21;
	public static final int CHP32 = 33;
	public static final int CHP33 = 25;
	public static final int CHP34 = 33;
	public static final int CHP35 = 27;
	public static final int CHP36 = 23;
}
